"""Initial Migration

Revision ID: 41853ecec8d9
Revises: d809e379fd36
Create Date: 2019-03-18 13:14:39.369548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41853ecec8d9'
down_revision = 'd809e379fd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_photos')
    # ### end Alembic commands ###
