"""Initial Migration

Revision ID: 7a13982b1683
Revises: 00eeb4a86cad
Create Date: 2019-02-28 10:23:01.450133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a13982b1683'
down_revision = '00eeb4a86cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('comments', 'comment')
    op.drop_column('comments', 'title')
    op.add_column('pitches', sa.Column('content', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'posted')
    op.drop_column('pitches', 'author')
    op.drop_column('pitches', 'body')
    op.drop_column('pitches', 'title')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'content')
    op.add_column('comments', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitch_id')
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
